package com.cenfotec.componentes.component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import org.apache.commons.math3.stat.correlation.PearsonsCorrelation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author enzoq
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("CALCULAR COEFICIENTE DE CORRELACIÓN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //105,4;116,8;103,2;124,7;137,9;126,9;112,3;129,10;118,7;105,6
        String[] array = separationsOfTextField();

        double[] numbers = initializeArrayOfAllTheNumbers(array);
        double arrayX[] = initializeCoordenates(numbers);
        double arrayY[] = initializeCoordenates(numbers);

        separateXsandYs(array, numbers, arrayX, arrayY);
        sumOfXsAndYs(numbers, arrayX, arrayY);

        setResultInLabel(arrayX, arrayY);
    }//GEN-LAST:event_jButton1MouseClicked
    private String[] separationsOfTextField() {
        String str = separateSemicolon();
        String[] array = separateCommas(str);
        return array;
    }

 
    private String separateSemicolon() {
        String listOfNumbers = this.jTextField1.getText();
        String[] firstArray = listOfNumbers.split(";");
        StringBuilder builder = new StringBuilder();
        for (String s : firstArray) {
            builder.append(s).append(",");
        }
        String str = builder.toString();
        return str;
    }

    private String[] separateCommas(String str) {
        String[] array = str.split(",");
        return array;
    }

    private double[] initializeArrayOfAllTheNumbers(String[] array) {
        double[] numbers = new double[array.length];
        return numbers;
    }

    private double[] initializeCoordenates(double[] numbers) {
        double array[] = new double[numbers.length / 2];
        return array;
    }

    private void sumOfXsAndYs(double[] numbers, double[] arrayX, double[] arrayY) {
        double sumX = 0, sumY = 0;
        int n = numbers.length / 2;
        for (int i = 0; i < n; i++) {
            sumX = sumX + arrayX[i];
            sumY = sumY + arrayY[i];
        }
    }

    private void separateXsandYs(String[] array, double[] numbers, double[] arrayX, double[] arrayY) throws NumberFormatException {
        int contX = 0, contY = 0;
        for (int i = 0; i < array.length; i++) {
            numbers[i] = Integer.parseInt(array[i]);
        }
        for (int i = 0; i < numbers.length; i++) {
            if (i % 2 == 0) {
                arrayX[contX] = numbers[i];
                contX++;
            } else {
                arrayY[contY] = numbers[i];
                contY++;
            }
        }
    }

    private double getPearsonsCorrelation(double[] arrayX, double[] arrayY) {
        //105,4;116,8;103,2;124,7;137,9;126,9;112,3;129,10;118,7;105,6
        PearsonsCorrelation p = new PearsonsCorrelation();
        return p.correlation(arrayX, arrayY);
    }

    private String getPearsonsCorrelationString(double[] arrayX, double[] arrayY) {
        //105,4;116,8;103,2;124,7;137,9;126,9;112,3;129,10;118,7;105,6
        PearsonsCorrelation p = new PearsonsCorrelation();
        String result = String.valueOf(p.correlation(arrayX, arrayY));
        return result;
    }

    private void setResultInLabel(double[] arrayX, double[] arrayY) {
        double resultOfCorrelation = getPearsonsCorrelation(arrayX, arrayY);
        SerachForTypeOfRelationship(resultOfCorrelation, arrayX, arrayY);
    }

    private void SerachForTypeOfRelationship(double resultOfCorrelation, double[] arrayX, double[] arrayY) {
        if (resultOfCorrelation == 0 || (resultOfCorrelation > 0 && resultOfCorrelation < 1) || (resultOfCorrelation < 0 && resultOfCorrelation > -1)) {
            this.jLabel1.setText(getPearsonsCorrelationString(arrayX, arrayY) + " -> Debil o nula relacion");
        } else if (resultOfCorrelation > 1) {
            this.jLabel1.setText(getPearsonsCorrelationString(arrayX, arrayY) + " -> Fuerte relacion positiva");
        } else if (resultOfCorrelation < -1) {
            this.jLabel1.setText(getPearsonsCorrelationString(arrayX, arrayY) + " -> Fuerte relacion negativa");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
